version: '3'

networks:
  traefik-proxy:
    external: true

services:
  traefik:
    image: traefik
    command: --docker --docker.domain=scobcov.me
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:traefik-dashboard.scobcov.me
      - traefik.port=8080
    container_name: traefik
    restart: always

  polikek:
    image: 'python:alpine'
    networks:
      - traefik-proxy
    volumes:
      - ./polikek:/home/app
    environment:
      - FLASK_ENV=production
    command: bash -c "
                    pip install -r requirements.txt &&
                    flask run"
    labels:
      - traefik.backend=polikek
      - traefik.frontend.rule=Host:polikek.scobcov.me
      - traefik.docker.network=traefik-proxy
      - traefik.port=5000
    container_name: polikek
    restart: always